#!/bin/sh

echo "Running tests..."

./gradlew test --daemon

status=$?

if [ "$status" -eq "0" ] ; then
  echo "✅ All tests passed"
else
  echo "❌ Some tests failed"
  exit 1
fi

echo "✅ Pre-push checks passed successfully!"
